# GLOBAL SETTINGS
title: lexjusto - is just my name # site title
author: lexjusto # i am ;)
description: > # site meta tag description
  Так себе бложек разработчика и скриптера ¯\_(ツ)_/¯
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.lxjst.com" # the base hostname & protocol for your site, e.g. https://google.com

# SEO PLUGIN
social:
  name: lexjusto
  links:
    - https://t.me/lexjusto
    - https://vk.com/lexjusto
    - https://twitter.com/lexjusto
    - https://instagram.com/lexjusto

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Главная', link: '/'}
  - {name: 'Обо мне', link: '/about'}
  - {name: 'Связаться со мной', link: '/contact'}

tagline: >
  Так себе бложек разработчика и скриптера ¯\_(ツ)_/¯

hero_img: hero-img.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: the.lexjusto@gmail.com # email for form submission

telegram_username: lexjusto
vk_username: lexjusto
twitter_username: lexjusto # replace with your_twitter_username or comment to remove link from footer
github_username:  lexjusto # replace with your_github_username or comment to remove link from footer
instagram_username: lexjusto # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: lexjusto # to enable comments replace with your_disqus_shortname

google_tag_manager: UA-114690824-2

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
